### ISSUE TITLE
Installer Download not available

### ISSUE THREAD

**Issue by avrovulcanxh607** [ystv/PiVTDesktop#3]
The binary link doesn't work any more, any chance sombody could uplaod it here as a release or send it directly to me?

**Comment by mstratford** [comment]
Hey there, sorry about that! I'll upload a new copy soon. Ping this if I haven't done it by tomorrow evening :)

**Comment by avrovulcanxh607** [comment]
Ok thanks

**Comment by mstratford** [comment]
@nat2001 Here you go, sorry about that. https://github.com/YSTV/PiVTDesktop/releases/tag/apr2018

Let us know how you get on (and what you use it for) 👍
