### ISSUE TITLE
Select files drop down menu is empty

### ISSUE THREAD

**Issue by GabiCbv** [ystv/PiVTDesktop#4]

**Comment by peskdale** [comment]
Hi - I’m afraid PiVT is no longer under development. 

The only suggestion I can make is to ensure that videos are stored in the directory listed in your PiVT server’s `config.yaml` (by default, this is  the root folder /videos).

If you are not using the config file, ensure that you are defining the correct directory using the `-f` command flag.

**Comment by GabiCbv** [comment]
Thank you i will try
